application:
  version: ${APP_VERSION:1.0.0}

spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8081